# Generated by Django 5.0.3 on 2024-05-16 21:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(default=None, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(500)])),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('period_of_stay', models.CharField(blank=True, choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=100, null=True)),
                ('baby_Number', models.IntegerField(unique=True)),
                ('parent_Name', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('brought_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='Full Day', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(default='Kabalagala', max_length=100)),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Enter a valid Country contact', regex='^(\\+256|0)\\d{9}$')])),
                ('education_Level', models.CharField(max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('next_of_kin', models.CharField(default=None, max_length=200)),
                ('recommended_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sitter_number', models.CharField(default=None, max_length=10, unique=True)),
                ('NIN', models.CharField(max_length=14, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(500)])),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=5000, max_digits=10, null=True)),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareApp.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(blank=True, choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0, null=True)),
                ('duration_of_pay', models.CharField(choices=[('Half day', 'Half day'), ('Full Day', 'Full Day'), ('Monthly Full Day', 'Monthly Full Day'), ('Monthly Half Day', 'Monthly Half Day')], max_length=100)),
                ('amount_paid', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000)])),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareApp.baby')),
                ('period_of_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareApp.period')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_on_duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'On Duty'), (False, 'Off Duty')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycareApp.sitter')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareApp.sitter_on_duty'),
        ),
        migrations.CreateModel(
            name='SitterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_baby', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('amount_paid', models.PositiveIntegerField(default=3000)),
                ('sitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareApp.sitter_on_duty')),
            ],
        ),
    ]
